spring.application.name=bff
server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=${ENTRA_ISSUER_URI}
app.security.audience=${ENTRA_API_AUDIENCE}

services.solicitudes.url=${SOLICITUDES_SERVICE_URL:http://localhost:8081}
services.catalogo.url=${CATALOGO_SERVICE_URL:http://localhost:8082}
